layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: agkozak
  # hackerrank: your_username
  # instagram: alexandros_kozak
  keybase: agkozak
  linkedin: agkozak
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: agkozak
  # unsplash: your_username
  # vk: your_username
  website: https://www.elsiecarlisle.com
  youtube: agkozak

topics:

  - name: ZSH
    web_url: https://github.com/topics/zsh
    image_url: https://avatars.githubusercontent.com/u/567410

  - name: Shell
    web_url: https://github.com/topics/shell
    image_url: https://bashlogo.com/img/symbol/png/full_colored_dark.png


  - name: dotfiles
    web_url: https://github.com/topics/dotfiles
    image_url: https://raw.githubusercontent.com/jglovier/dotfiles-logo/master/dotfiles-logo-icon.png

  - name: Audio EQ
    web_url: https://github.com/topics/equalizer
    image_url: http://simpleicon.com/wp-content/uploads/equalizer.png

#   - name: CSS
#     web_url: https://github.com/topics/css
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

#   - name: Web design

#   - name: Sass
#     web_url: https://github.com/topics/sass
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
